### ISSUE TITLE
Sourcemaps for React Apps with TS not working

### ISSUE THREAD

**Issue by davelosert** [virtualidentityag/gulp-build-framework#25]
While writing our React App with TypeScript (.tsx Files) we realized that we can not go into Debugging Mode in Chrome as it doesn't show our sources (under the _sources_ Tab in the _DevTools_). This is most probably due to missing Sourcemaps.

Maybe later this week I will have time to look into this, but I thought I'd already create an Issue to let you know about the problem.

**Comment by lhwparis** [comment]
@david will you create a pr for this issue?

**Comment by janrembold** [comment]
React was removed from the build framework so this isn't an issue for this project anymore.
