### ISSUE TITLE
Fix ftf.inc() bug not allowing sending data 

### ISSUE THREAD

**Issue by smohadjer** [virtualidentityag/gulp-build-framework#26]
In zetzerHelper.js inc() function should be updated as below.

`	inc: function(file, params) {
		return this.include(file, params);
	}
`

I wanted to create a PR, but I don't have push access to the repo.

**Comment by lhwparis** [comment]
@saeid you can create a pr from a fork in your personal github space. But I have you push rights now

**Comment by smohadjer** [comment]
I did so.

**Comment by timomayer** [comment]
PR merged. thanks @smohadjer
