### ISSUE TITLE
Add error callback to uglify task to help fixing broken builds

### ISSUE THREAD

**Issue by smohadjer** [virtualidentityag/gulp-build-framework#27]
Currently gulp's uglify.js breaks build process without reporting which file it chocked on or what the problem is. An error handler like below example would report both.

```
.pipe(uglify())
.on('error', function (err) { gutil.log(gutil.colors.red('[Error]'), err.toString()); })
```

**Comment by janrembold** [comment]
Feature added https://github.com/virtualidentityag/gulp-build-framework/tree/4.2.0
