### ISSUE TITLE
Current iconfont implementation can cause incorrect icon sizes in IE11

### ISSUE THREAD

**Issue by jhadenfeldt** [virtualidentityag/gulp-build-framework#32]
Currently the build framework expects one template for the iconfont css as can be seen here: https://github.com/virtualidentityag/frontend-framework/blob/master/app/resources/scss/fonts/iconfont/_icons.scss

This means, that after building the SCSS file, the [styles](https://github.com/virtualidentityag/frontend-framework/blob/master/app/resources/scss/fonts/iconfont/_icons.scss#L10) and the [icon mixins](https://github.com/virtualidentityag/frontend-framework/blob/master/app/resources/scss/fonts/iconfont/_icons.scss#L44) end up in the same file. 

This causes the following issue:

In some cases, we build separate SCSS files for larger components that are selectively added with our resource loader. These separate SCSS files use Icons in some cases, so we need to import the icons.scss in order to use the icons mixins:

![image](https://user-images.githubusercontent.com/959356/30227357-3989c160-948e-11e7-9899-25461e38f0fa.png)

But that means, that the icon styles are added again too:
![image](https://user-images.githubusercontent.com/959356/30227443-97077738-948e-11e7-8b3d-76f2782c1eb9.png)

And that is what causes an issue in IE11. For some reason, the `font-size: 68%;` stacks in IE11 and causes unwanted icon-sizes on those pages, that not only have the styles.css but also additional compontent css files added:

![image](https://user-images.githubusercontent.com/959356/30227683-58a7a386-948f-11e7-80c6-a784e37a9749.png)

My solution would be to separate the _icons.scss template in _iconStyles.scss and _icons.scss. This allows us, to import both in the styles.scss and only the _icons.scss in the components.

@jonerd & @janrembold, what do you guys think?

**Comment by lhwparis** [comment]
Thanks Jan. That's a valid case and solution sounds good!

**Comment by timomayer** [comment]
PR merged. thanks @jhadenfeldt !
