### ISSUE TITLE
Add convenient way to run multiple frameworks at once without conflicting ports

### ISSUE THREAD

**Issue by jhadenfeldt** [virtualidentityag/gulp-build-framework#7]
For some projects it can be convenient to run multiple frameworks at the same time with `gulp serve`. At the moment unfortunately this is not possible due to port conflicts. I propose to add a check if a port is not already in use before starting connect with https://github.com/indexzero/node-portfinder.

**Comment by timomayer** [comment]
hey jan, thanks for the suggestion. we have to keep in mind we would need that for more then gulp-connect. for example we also need to implement that for livereload ports too.

**Comment by janrembold** [comment]
We already have a configuration option for connect port. I just added an option for livereload port in release 4.0.2 

This is not an automatic port detection but it feels a little bit like an edge case to me, so this should do the job for now. If you agree please close the comment?

**Comment by janrembold** [comment]
no reaction for 5 months, closing this issue
